### ISSUE TITLE
Application does not start after OpenSSL update

### ISSUE THREAD

**Issue by habizzle** [Doccrazy/stash-electron#15]
After an OpenSSL update from  1.1.1.q-1 to 3.0.7-2 (from the Arch `core` repository), Stash does not start anymore:

```
Unhandled Error
Error: libcrypto.so.1.1: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.call (webpack:///external "../node_modules/nodegit/build/Release/nodegit.node":1:18)
    at n (webpack:///webpack/bootstrap:19:22)
```

Any help would be highly appreciated :)

I am using v1.2.2 of Stash.

**Comment by habizzle** [comment]
I just tried with the latest master version and I got this error message, maybe it helps:

```
Error
Cannot open /home/hannesb/workspace/stash-electron/.yarn/unplugged/nodegit-npm-0.28.0-alpha.13-aff180149f/node_modules/nodegit/build/Release/nodegit.node: Error: libcrypto.so.1.1: cannot open shared object file: No such file or directory
Call Stack
 eval
  yarn/unplugged/nodegit-npm-0.28.0-alpha.13-aff180149f/node_modules/nodegit/build/Release/nodegit.node:2:200
 Object../.yarn/unplugged/nodegit-npm-0.28.0-alpha.13-aff180149f/node_modules/nodegit/build/Release/nodegit.node
  defaultVendors-_yarn___virtual___electron-remote-virtual-a2a4ccd291_0_cache_electron-remote-n-8f0822.dev.js:6666:1
 Object.options.factory
  runtime~renderer.dev.js:705:31
 __webpack_require__
  runtime~renderer.dev.js:36:33
 fn
  runtime~renderer.dev.js:347:21
 eval
  yarn/unplugged/nodegit-npm-0.28.0-alpha.13-aff180149f/node_modules/nodegit/lib/nodegit.js:17:12
 Object../.yarn/unplugged/nodegit-npm-0.28.0-alpha.13-aff180149f/node_modules/nodegit/lib/nodegit.js
  defaultVendors-_yarn___virtual___electron-remote-virtual-a2a4ccd291_0_cache_electron-remote-n-8f0822.dev.js:11008:1
 Object.options.factory
  runtime~renderer.dev.js:705:31
 __webpack_require__
  runtime~renderer.dev.js:36:33
 fn
  runtime~renderer.dev.js:347:21
```

**Comment by habizzle** [comment]
I meanwhile made further investigations. I have not much knowledge about AppImage bundling and stuff so maybe I got something wrong :smile:.

My understanding is: `nodegit` is not compatible with OpenSSL 3 and as this project is not very well maintained we should not wait for them to get this right.

So wouldn't it be possible to just include `libcrypto.so.1.1` in the AppImage? I am wondering why this is not already the case? It is not included in https://github.com/AppImageCommunity/pkg2appimage/blob/master/excludelist but I am not sure if this list is even used during the build :see_no_evil:.
